/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlst.gui;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import qlst.dto.SanPhamXML;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import qlst.dao.*;
import qlst.dto.*;

/**
 *
 * @author Admin
 */

public class BanHangGUI extends javax.swing.JFrame {

    /**
     * Creates new form BanHangGUI
     */
    protected SanPhamDAO spDAO;
    protected SanPhamXML spXML;
    protected BillDAO billDAO;
    protected BillXML billXML;
    protected double tongTien;
    
    public BanHangGUI() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        spDAO = new SanPhamDAO();
        spXML = new SanPhamXML();
        billXML = new BillXML();
        billDAO = new BillDAO();
        showListBills(spDAO.readListProducts());
        showListBills2(billDAO.readListBills());
        
        DefaultTableModel spTable = (DefaultTableModel) tbl_danhSach.getModel();
        DefaultTableModel spTable2 = (DefaultTableModel) tbl_info.getModel();
        // Thêm sự kiện lắng nghe cho tbl_danhSach
        tbl_danhSach.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                // Kiểm tra xem có đang chọn hàng không
                if (!event.getValueIsAdjusting()) {
                    // Lấy chỉ số của hàng được chọn
                    int selectedRow = tbl_danhSach.getSelectedRow();
                    if (selectedRow != -1) { // Đảm bảo rằng đã chọn một hàng
                        // Lấy dữ liệu từ bảng và fill vào các textfield
                        fillProductFromSelectedRow();
                    }
                }
            }
        });
        
        txt_timKiem.addKeyListener(new KeyAdapter() {
        @Override
        public void keyReleased(KeyEvent e) {
            String searchText = txt_timKiem.getText().trim();
            searchProduct(searchText);
        }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_danhSach = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_soLuong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbl_tongTien = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_khachHang = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_info = new javax.swing.JTable();
        txt_ID = new javax.swing.JLabel();
        txt_ten = new javax.swing.JLabel();
        txt_donGia = new javax.swing.JLabel();
        btn_tongTien = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();
        btn_quayLai = new javax.swing.JButton();
        btn_lamMoi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_timKiem = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btn_xoa = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_danhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tên", "Số lượng", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_danhSach);
        if (tbl_danhSach.getColumnModel().getColumnCount() > 0) {
            tbl_danhSach.getColumnModel().getColumn(0).setResizable(false);
            tbl_danhSach.getColumnModel().getColumn(1).setResizable(false);
            tbl_danhSach.getColumnModel().getColumn(2).setResizable(false);
            tbl_danhSach.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153)), "Hoá đơn\n"));

        jLabel1.setText(" ID");

        jLabel2.setText(" Tên");

        jLabel3.setText(" Số lượng");

        jLabel4.setText(" Đơn giá");

        lbl_tongTien.setBackground(new java.awt.Color(204, 255, 204));
        lbl_tongTien.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lbl_tongTien.setForeground(new java.awt.Color(255, 0, 0));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText(" Khách hàng:");

        txt_khachHang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txt_khachHang.setForeground(new java.awt.Color(0, 0, 0));
        txt_khachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_khachHangActionPerformed(evt);
            }
        });

        tbl_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên", "Số lượng", "Đơn giá", "Tổng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_info);
        if (tbl_info.getColumnModel().getColumnCount() > 0) {
            tbl_info.getColumnModel().getColumn(0).setResizable(false);
            tbl_info.getColumnModel().getColumn(1).setResizable(false);
            tbl_info.getColumnModel().getColumn(2).setResizable(false);
            tbl_info.getColumnModel().getColumn(3).setResizable(false);
            tbl_info.getColumnModel().getColumn(4).setResizable(false);
        }

        btn_tongTien.setBackground(new java.awt.Color(255, 255, 204));
        btn_tongTien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_tongTien.setForeground(new java.awt.Color(255, 51, 51));
        btn_tongTien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/all.png"))); // NOI18N
        btn_tongTien.setText("Tổng tiền:");
        btn_tongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tongTienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                .addGap(33, 33, 33))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_soLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_khachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addComponent(txt_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_ten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_donGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_tongTien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_tongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_khachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txt_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txt_ten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txt_donGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_tongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_tongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        btn_luu.setBackground(new java.awt.Color(204, 255, 255));
        btn_luu.setForeground(new java.awt.Color(0, 0, 0));
        btn_luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/diskette.png"))); // NOI18N
        btn_luu.setText("In hoá đơn");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_quayLai.setBackground(new java.awt.Color(204, 204, 255));
        btn_quayLai.setForeground(new java.awt.Color(0, 0, 0));
        btn_quayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/return.png"))); // NOI18N
        btn_quayLai.setText("Quay lại");
        btn_quayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quayLaiActionPerformed(evt);
            }
        });

        btn_lamMoi.setBackground(new java.awt.Color(204, 255, 255));
        btn_lamMoi.setForeground(new java.awt.Color(0, 0, 0));
        btn_lamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/reset.png"))); // NOI18N
        btn_lamMoi.setText("Làm mới");
        btn_lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/search16.png"))); // NOI18N
        jLabel5.setText("Tìm Kiếm:");

        txt_timKiem.setBackground(new java.awt.Color(204, 255, 255));
        txt_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timKiemActionPerformed(evt);
            }
        });

        btn_them.setBackground(new java.awt.Color(204, 255, 255));
        btn_them.setForeground(new java.awt.Color(0, 0, 0));
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/add.png"))); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText(" Danh sách sản phẩm hiện có:");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153)));

        btn_xoa.setBackground(new java.awt.Color(204, 255, 255));
        btn_xoa.setForeground(new java.awt.Color(0, 0, 0));
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/delete.png"))); // NOI18N
        btn_xoa.setText("Xoá");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_sua.setBackground(new java.awt.Color(204, 255, 255));
        btn_sua.setForeground(new java.awt.Color(0, 0, 0));
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/editing.png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_luu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_lamMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_quayLai))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_timKiem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_sua)
                    .addComponent(btn_xoa)
                    .addComponent(btn_luu)
                    .addComponent(btn_lamMoi)
                    .addComponent(btn_quayLai))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void searchProduct(String searchText) {
        DefaultTableModel model = (DefaultTableModel) tbl_danhSach.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tbl_danhSach.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + Pattern.quote(searchText)));
    }
    

    public void fillProductFromSelectedRow() {
        int selectedRow = tbl_danhSach.getSelectedRow();
        if (selectedRow != -1) { // Đảm bảo rằng đã chọn một hàng
            txt_ID.setText(tbl_danhSach.getValueAt(selectedRow, 0).toString());
            txt_ten.setText(tbl_danhSach.getValueAt(selectedRow, 1).toString());
            txt_soLuong.setText(tbl_danhSach.getModel().getValueAt(selectedRow, 2).toString());
            txt_donGia.setText(tbl_danhSach.getValueAt(selectedRow, 3).toString());
            lbl_tongTien.setText("");
        }
    }
     //check form ten khach hang
    private boolean checkKhach(){
        String name = txt_khachHang.getText();
        if(name == null || "".equals(name.trim())){
            txt_khachHang.requestFocus();
            return false;
        }
        return true;
    }
        
    public void showListBills(List<SanPhamDTO> list) {
        DefaultTableModel spTable = (DefaultTableModel) tbl_danhSach.getModel();
        
        spTable.setRowCount(0);

        for (SanPhamDTO sp : list) {
            Object[] rowSP = new Object[8];
            rowSP[0] = sp.getID();
            rowSP[1] = sp.getTenSP();
            rowSP[2] = sp.getSoLuong();
            rowSP[3] = sp.getGiaDeXuat();
            spTable.addRow(rowSP);
        }
    }
    
    public void showListBills2(List<BillDTO> list) {
        DefaultTableModel spTable = (DefaultTableModel) tbl_info.getModel();
        
        spTable.setRowCount(0);

        for (BillDTO sp : list) {
            Object[] rowSP = new Object[8];
            rowSP[0] = sp.getID();
            rowSP[1] = sp.getTenHang();
            rowSP[2] = sp.getSoLuong();
            rowSP[3] = sp.getGiaBan();
            rowSP[4] = sp.getSoLuong() * sp.getGiaBan();
            spTable.addRow(rowSP);
        }
    }
    
    public void keepRoot(){
        for (SanPhamDTO sp : spDAO.readListProducts()) {
            spDAO.delete(sp);
    }   

    }
    private void btn_lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        txt_ID.setText("");
        txt_ten.setText("");
        txt_donGia.setText("");
        txt_soLuong.setText("");
        txt_khachHang.setText("");
    }//GEN-LAST:event_btn_lamMoiActionPerformed
    
    
    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
        PrintBillGUI printBillGUI = new PrintBillGUI();
        printBillGUI.setBanHangGUI(this); // Truyền tham chiếu của BanHangGUI hiện tại vào PrintBillGUI
        billDAO.keepRoot();
        printBillGUI.setVisible(true);
        printBillGUI.show();
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        BillDTO sp = new BillDTO();
        sp.setID(txt_ID.getText());
        sp.setTenHang(txt_ten.getText());
        sp.setSoLuong(Integer.parseInt(txt_soLuong.getText()));
        sp.setGiaBan(Double.parseDouble(txt_donGia.getText()));
        DefaultTableModel spTable2 = (DefaultTableModel) tbl_info.getModel();
        DefaultTableModel spTable = (DefaultTableModel) tbl_danhSach.getModel();
        this.billDAO.add(sp);
        
    }//GEN-LAST:event_btn_themActionPerformed
    
    
    public String getKhach(){
        return txt_khachHang.getText();
    }
    private void txt_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timKiemActionPerformed

    private void txt_khachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_khachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_khachHangActionPerformed

    private void btn_quayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quayLaiActionPerformed
        // TODO add your handling code here:
        MenuGUI mn = new MenuGUI();
        mn.show();
        dispose();
    }//GEN-LAST:event_btn_quayLaiActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        int selectedRow = tbl_info.getSelectedRow();
        if (selectedRow != -1) {
            String id = tbl_info.getValueAt(selectedRow, 0).toString();
            // Tạo một đối tượng BillDTO từ ID
            BillDTO bill = new BillDTO();
            bill.setID(id);
            // Gọi phương thức delete() từ đối tượng BillDAO để xóa hóa đơn
            if (billDAO.delete(bill)) {
                JOptionPane.showMessageDialog(null, "Xoá khỏi giỏ hàng thành công!");
                // Cập nhật lại bảng thông tin hóa đơn
                showListBills2(billDAO.readListBills());
            } else {
                JOptionPane.showMessageDialog(null, "Xoá khỏi giỏ hàng thất bại!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một sản phẩm để xoá!");
        }
        DefaultTableModel spTable2 = (DefaultTableModel) tbl_info.getModel();
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_info.getSelectedRow();
        if (selectedRow != -1) {
            String id = tbl_info.getValueAt(selectedRow, 0).toString();
            
            String soLuongMoi = JOptionPane.showInputDialog(null, "Nhập số lượng mới:");

            // Kiểm tra nếu tên khách hàng mới hoặc số lượng mới không rỗng
            if (soLuongMoi != null && !soLuongMoi.isEmpty()) {
                // Tạo một đối tượng BillDTO từ thông tin mới
                BillDTO bill = new BillDTO();
                bill.setID(id);
                bill.setGiaBan(Double.parseDouble(txt_donGia.getText()));
                bill.setSoLuong(Integer.parseInt(soLuongMoi));
                billDAO.edit(bill);
                // Cập nhật lại bảng thông tin hóa đơn
                showListBills2(billDAO.readListBills());
                JOptionPane.showMessageDialog(null, "Sửa thành công!");
            } else {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn!");
        }
        DefaultTableModel spTable2 = (DefaultTableModel) tbl_info.getModel();
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_tongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tongTienActionPerformed
        // TODO add your handling code here:
        lbl_tongTien .setText(String.valueOf(calculateTotalSum()));
    }//GEN-LAST:event_btn_tongTienActionPerformed
        private double calculateTotalSum() {
        DefaultTableModel model = (DefaultTableModel) tbl_info.getModel();
        double totalSum = 0;

        for (int i = 0; i < model.getRowCount(); i++) {
            double price = Double.parseDouble(model.getValueAt(i, 3).toString());
            int quantity = Integer.parseInt(model.getValueAt(i, 2).toString());
            totalSum += price * quantity;
        }

        return totalSum;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BanHangGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_lamMoi;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_quayLai;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_tongTien;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_tongTien;
    private javax.swing.JTable tbl_danhSach;
    private javax.swing.JTable tbl_info;
    private javax.swing.JLabel txt_ID;
    private javax.swing.JLabel txt_donGia;
    private javax.swing.JTextField txt_khachHang;
    private javax.swing.JTextField txt_soLuong;
    private javax.swing.JLabel txt_ten;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables
}
