/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlst.gui;

/**
 *
 * @author Admin
 */
public class MenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuGUI() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lbl_ten = new javax.swing.JLabel();
        btn_dangXuat = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        btn_thoat = new javax.swing.JButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        btn_danhMuc = new javax.swing.JButton();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        btn_hoaDon = new javax.swing.JButton();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        btn_thongKe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jLayeredPane2.setBackground(new java.awt.Color(193, 193, 241));
        jLayeredPane2.setEnabled(false);
        jLayeredPane2.setOpaque(true);

        jLayeredPane1.setBackground(new java.awt.Color(33, 30, 79));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.add(lbl_ten);
        lbl_ten.setBounds(240, 10, 170, 40);

        btn_dangXuat.setBackground(new java.awt.Color(19, 17, 48));
        btn_dangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_dangXuat.setForeground(new java.awt.Color(204, 255, 255));
        btn_dangXuat.setText("Đăng xuất");
        btn_dangXuat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_dangXuat.setContentAreaFilled(false);
        btn_dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangXuatActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btn_dangXuat);
        btn_dangXuat.setBounds(410, 10, 110, 40);

        jLayeredPane2.add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 0, 510, 60);

        jLayeredPane3.setBackground(new java.awt.Color(204, 204, 204));
        jLayeredPane3.setOpaque(true);

        btn_thoat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_thoat.setForeground(new java.awt.Color(0, 0, 0));
        btn_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/logout.png"))); // NOI18N
        btn_thoat.setText("Thoát");
        btn_thoat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_thoat.setContentAreaFilled(false);
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        jLayeredPane3.setLayer(btn_thoat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(0, 75, Short.MAX_VALUE)
                .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_thoat)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLayeredPane2.add(jLayeredPane3);
        jLayeredPane3.setBounds(260, 60, 260, 50);

        jLayeredPane4.setBackground(new java.awt.Color(153, 153, 153));
        jLayeredPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane4.setOpaque(true);

        btn_danhMuc.setBackground(new java.awt.Color(19, 17, 48));
        btn_danhMuc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_danhMuc.setForeground(new java.awt.Color(0, 0, 0));
        btn_danhMuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/sort.png"))); // NOI18N
        btn_danhMuc.setText("Danh mục");
        btn_danhMuc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_danhMuc.setContentAreaFilled(false);
        btn_danhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_danhMucActionPerformed(evt);
            }
        });

        jLayeredPane4.setLayer(btn_danhMuc, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btn_danhMuc)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_danhMuc)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jLayeredPane2.add(jLayeredPane4);
        jLayeredPane4.setBounds(160, 110, 250, 50);

        jLayeredPane5.setBackground(new java.awt.Color(102, 102, 102));
        jLayeredPane5.setForeground(new java.awt.Color(153, 153, 153));
        jLayeredPane5.setOpaque(true);

        btn_hoaDon.setBackground(new java.awt.Color(19, 17, 48));
        btn_hoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_hoaDon.setForeground(new java.awt.Color(255, 255, 0));
        btn_hoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/bill-32.png"))); // NOI18N
        btn_hoaDon.setText("Hoá đơn");
        btn_hoaDon.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_hoaDon.setContentAreaFilled(false);
        btn_hoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hoaDonActionPerformed(evt);
            }
        });

        jLayeredPane5.setLayer(btn_hoaDon, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(btn_hoaDon)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_hoaDon)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLayeredPane2.add(jLayeredPane5);
        jLayeredPane5.setBounds(80, 160, 260, 50);

        jLayeredPane6.setBackground(new java.awt.Color(51, 51, 51));
        jLayeredPane6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane6.setOpaque(true);

        btn_thongKe.setBackground(new java.awt.Color(19, 17, 48));
        btn_thongKe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_thongKe.setForeground(new java.awt.Color(204, 255, 255));
        btn_thongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/statsBlue.png"))); // NOI18N
        btn_thongKe.setText("Thống kê");
        btn_thongKe.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_thongKe.setContentAreaFilled(false);
        btn_thongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thongKeActionPerformed(evt);
            }
        });

        jLayeredPane6.setLayer(btn_thongKe, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btn_thongKe)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btn_thongKe)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLayeredPane2.add(jLayeredPane6);
        jLayeredPane6.setBounds(0, 210, 250, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangXuatActionPerformed
        // TODO add your handling code here:
        LoginGUI lg = new LoginGUI();
        lg.show();
        dispose();
    }//GEN-LAST:event_btn_dangXuatActionPerformed

    private void btn_thongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thongKeActionPerformed
        // TODO add your handling code here:
        ThongKeGUI tk = new ThongKeGUI();
        tk.show();
        dispose();
    }//GEN-LAST:event_btn_thongKeActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void btn_danhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_danhMucActionPerformed
        // TODO add your handling code here:
        DanhMucGUI dm = new DanhMucGUI();
        dm.show();
        dispose();
    }//GEN-LAST:event_btn_danhMucActionPerformed

    private void btn_hoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hoaDonActionPerformed
        // TODO add your handling code here:
        BanHangGUI bh = new BanHangGUI();
        bh.show();
        dispose();
    }//GEN-LAST:event_btn_hoaDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangXuat;
    private javax.swing.JButton btn_danhMuc;
    private javax.swing.JButton btn_hoaDon;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_thongKe;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLabel lbl_ten;
    // End of variables declaration//GEN-END:variables
}
